Testing
YunoHost-Apps/nitter_ynh pull request #22
Opened 2022-06-20 21:29 UTC by ericgaspar

- Add config panel

2022-06-20 21:29 UTC, ericgaspar commented
!testme

2022-06-20 21:37 UTC, Jules-Bertholet requested changes

2022-06-20 21:37 UTC, Jules-Bertholet commented on config_panel.toml
> +        bind = "replaceInstagram:__FINALPATH__/nitter.conf"
```suggestion
        help = "Replace Reddit links with a Libreddit instance"
        bind = "replaceReddit:__FINALPATH__/nitter.conf"
```

2022-06-20 22:30 UTC, Jules-Bertholet approved these changes

2022-06-23 06:46 UTC, ericgaspar commented
!testme

2022-06-23 18:16 UTC, merged